### ISSUE TITLE
`mx.ivyleav.es` is broken

### ISSUE THREAD

**Issue by nicoonoclaste** [AstraLuma/mx-master-list#17]
The certificate isn't valid for `mx.ivyleav.es`, and then one gets a 404.
I'm guessing that name in DNS points at a server which isn't configured (HTTP-wise) for that host.

**Comment by AstraLuma** [comment]
I must have confused it for a mail domain when I switched DNS providers.

**Comment by AstraLuma** [comment]
It's been fixed at the origin. Waiting for DNS to propagate.
